language: ruby
jdk:
#  - oraclejdk8 -- will turn this on once scala can be excluded
  - oraclejdk7
rvm:
  - 2.2.5
  - 2.3.1
  - jruby-1.7.25
  - jruby-9.0.5.0
git:
  depth: 10
scala:
#  - 2.10.0
  - 2.9.2
#  - 2.9.1
#  - 2.8.1
install:
  - source ci-setup.sh
  - export JRUBY_OPTS="-J-XX:MaxPermSize=312m -J-Xmx700M"
  - export JAVA_OPTS="-Xmx700m -XX:MaxPermSize=312m"
script: rake ci
notifications:
  email:
    recipients:
      - commits@buildr.apache.org
      - donaldp@apache.org
      - peter@realityforge.org
      - toulmean@apache.org
    on_success: always
    on_failure: always
notifications:
  irc: "irc.freenode.org#buildr"
